### ISSUE TITLE
Feature Request: Export to nbt file

### ISSUE THREAD

**Issue by BakermanLP** [malte0811/NBTEdit#1]
Hello there,

I am a modpack maker and would love to have one additional feature.

For the mod Terrain Control I need some nbt files. And until now I haven't found a solution for that. Your mod is nice to change the NBT data of a Block. But it would be very nice to export the nbt data to a nbt file. This should be in a normal nbt format and not json or anything like that.

Thanks for reading

Michael (aka BakermanLP)

**Comment by malte0811** [comment]
Sorry for the delay, I kind of forgot about this...
The feature is implemented now (even though I assume you found a different solution by now), the build should be on curseforge in a minute. You can export to a file by right-clicking a tag compound and selecting "Write tag to file".

**Comment by BakermanLP** [comment]
Great. Thank you
