### ISSUE TITLE
Batch edit taking incredibly long

### ISSUE THREAD

**Issue by sugiharaxo** [malte0811/NBTEdit#12]
I'm mass editing a byte tag in all of the chunks of a 2000x2000 world that I pregenerated for my server. I expected it to take a few seconds but its been going at it for more than 4 hours now.

gif: https://gyazo.com/e1241503dcc5efd077f4fdb5f3ce23b9

I have an Intel i5-8600K @3.6GHz

**Comment by malte0811** [comment]
You're using NBTExplorer, not NBTEdit. NBTEdit is a mod you can use to edit (tile) entity NBT in-game. I don't know who develops NBTExplorer, but it isn't me.

**Comment by sugiharaxo** [comment]
Lol, so sorry about that. Please delete it :)
