### ISSUE TITLE
Problem with /nbtedit [no command]

### ISSUE THREAD

**Issue by andrew000** [malte0811/NBTEdit#14]
No command in minecraft.

Screenshot: https://prnt.sc/uofwjp

**Comment by malte0811** [comment]
NBTEdit uses Forge, not Fabric.

**Comment by andrew000** [comment]
How about porting a mod to Fabric?

**Comment by andrew000** [comment]
> NBTEdit uses Forge, not Fabric.

How about porting a mod to Fabric?
