### ISSUE TITLE
[1.10.2] Compilation from source fails

### ISSUE THREAD

**Issue by Brycey92** [malte0811/NBTEdit#5]
Upon cloning the repository's 1.10 branch and running `gradlew setupDecompWorkspace eclipse build`, eclipse shows numerous errors relating to things missing from the mcp mappings, and the gradle build fails because it can't find classes from Immersive Engineering. Additionally, gradle gives a warning that 1.9.4 mappings are being used to compile the mod for 1.10.2.

**Comment by malte0811** [comment]
I don't know about the MCP mappings, but you need to manually add an IE build. Make a folder in the main directory called libs and put in an IE build (I'm not sure whether it needs to be a deobf build or not in 1.10). That should fix those errors. There shouldn't be any missing mappings unless you merged commits from 1.11 or 1.12. The warning about mappings for 1.9.4 is not ideal, but doesn't break anything.

**Comment by Brycey92** [comment]
I haven't cherry picked any commits yet from different branches, but I added the latest deobf IE jar file to the libs folder and gradle compiled the mod successfully. However, eclipse still seems to be unaware of several fields and functions from Minecraft, making development a challenge.

**Comment by Brycey92** [comment]
Still looking to contribute to this mod. Please let me know if you find a solution.

**Comment by Brycey92** [comment]
I'm switching my pack from 1.10.2 to 1.12.2, so I no longer need this issue fixed for 1.10.
