### ISSUE TITLE
No NBTEdit window appears. MC 1.14.4 Forge 28.1.20

### ISSUE THREAD

**Issue by JillSwift** [malte0811/NBTEdit#8]
When facing a block and typing the command /nbtedit, no nbtedit window appears.

Minecraft 1.14.4
Forge 28.1.20
Java OpenJDK 1.8.0_222-B05 (Linux 64 bit, kernel 5.2.11)

Might be related or is "java.awt.HeadlessException: null" issue? (Full log attached)
[latest.log](https://github.com/malte0811/NBTEdit/files/3667472/latest.log)

**Comment by malte0811** [comment]
I have 2 ideas for possible causes. Please try with [this debug build of NBTEdit](https://drive.google.com/open?id=1Dx17HeUJiZwyLvJLNMYI9j-K7Il9A3T5), tell me whether it works (it probably will) and upload a log *even if it works* (ideally `debug.log`, what you uploaded before looks like `latest.log` to me). I'd like to know which one of my ideas actually fixed the problem.

**Comment by JillSwift** [comment]
Didn't work
[no_voxelmap_debug.log](https://github.com/malte0811/NBTEdit/files/3667551/no_voxelmap_debug.log)
Additionally, it made VoxelMap freak out:
[debug.log](https://github.com/malte0811/NBTEdit/files/3667554/debug.log)
[crash-2019-09-29_09.37.57-client.txt](https://github.com/malte0811/NBTEdit/files/3667555/crash-2019-09-29_09.37.57-client.txt)

**Comment by malte0811** [comment]
Are you using a headless JVM? And what launcher are you using? From the log I'd say that my first fix worked, but for some reason Java is failing to load shared libraries for X11.

**Comment by JillSwift** [comment]
Nope, using the full install with GUI stuff. Just made sure by re-installing it and its dependencies.
[debug.log](https://github.com/malte0811/NBTEdit/files/3667600/debug.log) ⬅️ ran again after

Using the official [Mojang launcher v2.1.5965](https://aur.archlinux.org/packages/minecraft-launcher).

**Comment by malte0811** [comment]
Is [this build](https://drive.google.com/open?id=1sHPMxnCs3CFK9rafiJuXYcOk1nbRPZVq) better? It looks like one of your other mods accessed some things related to AWT before I reset the headless state; resetting these parts of AWT seems to be nontrivial, so I just reset the headless state as early as I can now.

**Comment by JillSwift** [comment]
Perfect. Even VoxelMap was happy with it.
[successful_run_debug.log](https://github.com/malte0811/NBTEdit/files/3668001/successful_run_debug.log)
